// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/betting.proto

package bettingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BettingService_PlaceBet_FullMethodName          = "/betting.BettingService/PlaceBet"
	BettingService_CreditAmount_FullMethodName      = "/betting.BettingService/CreditAmount"
	BettingService_SaveBet_FullMethodName           = "/betting.BettingService/SaveBet"
	BettingService_UpdateBetResult_FullMethodName   = "/betting.BettingService/UpdateBetResult"
	BettingService_GetLastRound_FullMethodName      = "/betting.BettingService/GetLastRound"
	BettingService_CreateRound_FullMethodName       = "/betting.BettingService/CreateRound"
	BettingService_UpdateRoundStatus_FullMethodName = "/betting.BettingService/UpdateRoundStatus"
	BettingService_SaveRoundResult_FullMethodName   = "/betting.BettingService/SaveRoundResult"
	BettingService_RefundRound_FullMethodName       = "/betting.BettingService/RefundRound"
)

// BettingServiceClient is the client API for BettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BettingServiceClient interface {
	PlaceBet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetResponse, error)
	CreditAmount(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error)
	SaveBet(ctx context.Context, in *SaveBetRequest, opts ...grpc.CallOption) (*SaveBetResponse, error)
	UpdateBetResult(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error)
	GetLastRound(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoundResponse, error)
	CreateRound(ctx context.Context, in *CreateRoundRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateRoundStatus(ctx context.Context, in *UpdateRoundStatusRequest, opts ...grpc.CallOption) (*Empty, error)
	SaveRoundResult(ctx context.Context, in *SaveRoundResultRequest, opts ...grpc.CallOption) (*Empty, error)
	RefundRound(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*Empty, error)
}

type bettingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBettingServiceClient(cc grpc.ClientConnInterface) BettingServiceClient {
	return &bettingServiceClient{cc}
}

func (c *bettingServiceClient) PlaceBet(ctx context.Context, in *BetRequest, opts ...grpc.CallOption) (*BetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetResponse)
	err := c.cc.Invoke(ctx, BettingService_PlaceBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CreditAmount(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditResponse)
	err := c.cc.Invoke(ctx, BettingService_CreditAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveBet(ctx context.Context, in *SaveBetRequest, opts ...grpc.CallOption) (*SaveBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveBetResponse)
	err := c.cc.Invoke(ctx, BettingService_SaveBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) UpdateBetResult(ctx context.Context, in *UpdateBetRequest, opts ...grpc.CallOption) (*UpdateBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBetResponse)
	err := c.cc.Invoke(ctx, BettingService_UpdateBetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) GetLastRound(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoundResponse)
	err := c.cc.Invoke(ctx, BettingService_GetLastRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) CreateRound(ctx context.Context, in *CreateRoundRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BettingService_CreateRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) UpdateRoundStatus(ctx context.Context, in *UpdateRoundStatusRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BettingService_UpdateRoundStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) SaveRoundResult(ctx context.Context, in *SaveRoundResultRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BettingService_SaveRoundResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bettingServiceClient) RefundRound(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BettingService_RefundRound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BettingServiceServer is the server API for BettingService service.
// All implementations must embed UnimplementedBettingServiceServer
// for forward compatibility.
type BettingServiceServer interface {
	PlaceBet(context.Context, *BetRequest) (*BetResponse, error)
	CreditAmount(context.Context, *CreditRequest) (*CreditResponse, error)
	SaveBet(context.Context, *SaveBetRequest) (*SaveBetResponse, error)
	UpdateBetResult(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error)
	GetLastRound(context.Context, *Empty) (*RoundResponse, error)
	CreateRound(context.Context, *CreateRoundRequest) (*Empty, error)
	UpdateRoundStatus(context.Context, *UpdateRoundStatusRequest) (*Empty, error)
	SaveRoundResult(context.Context, *SaveRoundResultRequest) (*Empty, error)
	RefundRound(context.Context, *RefundRequest) (*Empty, error)
	mustEmbedUnimplementedBettingServiceServer()
}

// UnimplementedBettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBettingServiceServer struct{}

func (UnimplementedBettingServiceServer) PlaceBet(context.Context, *BetRequest) (*BetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedBettingServiceServer) CreditAmount(context.Context, *CreditRequest) (*CreditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreditAmount not implemented")
}
func (UnimplementedBettingServiceServer) SaveBet(context.Context, *SaveBetRequest) (*SaveBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveBet not implemented")
}
func (UnimplementedBettingServiceServer) UpdateBetResult(context.Context, *UpdateBetRequest) (*UpdateBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBetResult not implemented")
}
func (UnimplementedBettingServiceServer) GetLastRound(context.Context, *Empty) (*RoundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastRound not implemented")
}
func (UnimplementedBettingServiceServer) CreateRound(context.Context, *CreateRoundRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRound not implemented")
}
func (UnimplementedBettingServiceServer) UpdateRoundStatus(context.Context, *UpdateRoundStatusRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoundStatus not implemented")
}
func (UnimplementedBettingServiceServer) SaveRoundResult(context.Context, *SaveRoundResultRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveRoundResult not implemented")
}
func (UnimplementedBettingServiceServer) RefundRound(context.Context, *RefundRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundRound not implemented")
}
func (UnimplementedBettingServiceServer) mustEmbedUnimplementedBettingServiceServer() {}
func (UnimplementedBettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BettingServiceServer will
// result in compilation errors.
type UnsafeBettingServiceServer interface {
	mustEmbedUnimplementedBettingServiceServer()
}

func RegisterBettingServiceServer(s grpc.ServiceRegistrar, srv BettingServiceServer) {
	// If the following call panics, it indicates UnimplementedBettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BettingService_ServiceDesc, srv)
}

func _BettingService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_PlaceBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).PlaceBet(ctx, req.(*BetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CreditAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CreditAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CreditAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CreditAmount(ctx, req.(*CreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SaveBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveBet(ctx, req.(*SaveBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_UpdateBetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).UpdateBetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_UpdateBetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).UpdateBetResult(ctx, req.(*UpdateBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_GetLastRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).GetLastRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_GetLastRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).GetLastRound(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_CreateRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).CreateRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_CreateRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).CreateRound(ctx, req.(*CreateRoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_UpdateRoundStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoundStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).UpdateRoundStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_UpdateRoundStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).UpdateRoundStatus(ctx, req.(*UpdateRoundStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_SaveRoundResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRoundResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).SaveRoundResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_SaveRoundResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).SaveRoundResult(ctx, req.(*SaveRoundResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BettingService_RefundRound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BettingServiceServer).RefundRound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BettingService_RefundRound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BettingServiceServer).RefundRound(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BettingService_ServiceDesc is the grpc.ServiceDesc for BettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "betting.BettingService",
	HandlerType: (*BettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBet",
			Handler:    _BettingService_PlaceBet_Handler,
		},
		{
			MethodName: "CreditAmount",
			Handler:    _BettingService_CreditAmount_Handler,
		},
		{
			MethodName: "SaveBet",
			Handler:    _BettingService_SaveBet_Handler,
		},
		{
			MethodName: "UpdateBetResult",
			Handler:    _BettingService_UpdateBetResult_Handler,
		},
		{
			MethodName: "GetLastRound",
			Handler:    _BettingService_GetLastRound_Handler,
		},
		{
			MethodName: "CreateRound",
			Handler:    _BettingService_CreateRound_Handler,
		},
		{
			MethodName: "UpdateRoundStatus",
			Handler:    _BettingService_UpdateRoundStatus_Handler,
		},
		{
			MethodName: "SaveRoundResult",
			Handler:    _BettingService_SaveRoundResult_Handler,
		},
		{
			MethodName: "RefundRound",
			Handler:    _BettingService_RefundRound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/betting.proto",
}
