databases:
  - name: color-trading-db
    databaseName: color_trading
    user: postgres
    plan: free

services:
  - type: web
    name: backend-go
    plan: free
    env: docker
    dockerfilePath: ./backend-go/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: color-trading-db
          property: connectionString
      - key: PORT
        value: "8080" # Render public HTTP port

  - type: web
    name: engine-server
    plan: free
    env: docker
    dockerfilePath: ./engine-server/Dockerfile
    envVars:
      - key: REDIS_URL
        sync: false # You must set this in the Render Dashboard
      - key: BACKEND_GO_GRPC_URL
        value: "backend-go:8082" # Render internal network
      - key: PORT
        value: "8080" # Dummy HTTP port for Render health checks

  - type: web
    name: ws-server-go
    plan: free
    env: docker
    dockerContext: .
    dockerfilePath: ./ws-server-go/Dockerfile
    envVars:
      - key: REDIS_URL
        sync: false # You must set this in the Render Dashboard
      - key: BACKEND_GO_GRPC_URL
        value: "backend-go:8082"
      - key: ENGINE_SERVER_GRPC_URL
        value: "engine-server:8083"
      - key: PORT
        value: "8090" # WS HTTP port
