services:
  - type: web
    name: backend-go
    plan: free
    env: docker
    rootDir: backend
    dockerfilePath: backend-go/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgresql://dpkv_trading_user:ELOzxm7VeO8JWkYhCLW0LxZ4dNcVaPME@dpg-d7b9e3ea2pns73be1rfg-a/dpkv_trading"
      - key: PORT
        value: "8080" 

  - type: web
    name: engine-server
    plan: free
    env: docker
    rootDir: backend
    dockerfilePath: engine-server/Dockerfile
    envVars:
      - key: REDIS_URL
        value: "rediss://default:gQAAAAAAAXHFAAIncDIxZDRkNTNjOTIyMmU0Mzg2YmI3Y2Y2ZTNlZWM5MTI1OHAyOTQ2NjE@open-horse-94661.upstash.io:6379"
      - key: BACKEND_GO_GRPC_URL
        value: "backend-go:8082" 
      - key: PORT
        value: "8080"

  - type: web
    name: ws-server-go
    plan: free
    env: docker
    rootDir: backend
    dockerContext: .
    dockerfilePath: ws-server-go/Dockerfile
    envVars:
      - key: REDIS_URL
        value: "rediss://default:gQAAAAAAAXHFAAIncDIxZDRkNTNjOTIyMmU0Mzg2YmI3Y2Y2ZTNlZWM5MTI1OHAyOTQ2NjE@open-horse-94661.upstash.io:6379"
      - key: BACKEND_GO_GRPC_URL
        value: "backend-go:8082"
      - key: ENGINE_SERVER_GRPC_URL
        value: "engine-server:8083"
      - key: PORT
        value: "8090" 
