server {
    listen 80;
    server_name dpkvtrading.online api.dpkvtrading.online;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dpkvtrading.online api.dpkvtrading.online;

    ssl_certificate /etc/letsencrypt/live/dpkvtrading.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dpkvtrading.online/privkey.pem;

    server_tokens off;

    location /api {
        limit_req zone=api_limit burst=20;

        proxy_pass http://backend-go:8080;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header X-Internal-Secret dpkv123123;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws {
        proxy_pass http://ws-server-go:8090;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Internal-Secret dpkv123123;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
