// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/engine.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	mi := &file_proto_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBetRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceBetRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PlaceBetRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type PlaceBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetResponse) Reset() {
	*x = PlaceBetResponse{}
	mi := &file_proto_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetResponse) ProtoMessage() {}

func (x *PlaceBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetResponse.ProtoReflect.Descriptor instead.
func (*PlaceBetResponse) Descriptor() ([]byte, []int) {
	return file_proto_engine_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaceBetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_engine_proto protoreflect.FileDescriptor

const file_proto_engine_proto_rawDesc = "" +
	"\n" +
	"\x12proto/engine.proto\x12\x06engine\"X\n" +
	"\x0fPlaceBetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"F\n" +
	"\x10PlaceBetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2U\n" +
	"\rEngineService\x12D\n" +
	"\x0fRequestPlaceBet\x12\x17.engine.PlaceBetRequest\x1a\x18.engine.PlaceBetResponseB3Z1Color-Trading/backend/ws-server-go/proto/enginepbb\x06proto3"

var (
	file_proto_engine_proto_rawDescOnce sync.Once
	file_proto_engine_proto_rawDescData []byte
)

func file_proto_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)))
	})
	return file_proto_engine_proto_rawDescData
}

var file_proto_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_engine_proto_goTypes = []any{
	(*PlaceBetRequest)(nil),  // 0: engine.PlaceBetRequest
	(*PlaceBetResponse)(nil), // 1: engine.PlaceBetResponse
}
var file_proto_engine_proto_depIdxs = []int32{
	0, // 0: engine.EngineService.RequestPlaceBet:input_type -> engine.PlaceBetRequest
	1, // 1: engine.EngineService.RequestPlaceBet:output_type -> engine.PlaceBetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_engine_proto_init() }
func file_proto_engine_proto_init() {
	if File_proto_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_proto_rawDesc), len(file_proto_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_proto_depIdxs,
		MessageInfos:      file_proto_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_proto = out.File
	file_proto_engine_proto_goTypes = nil
	file_proto_engine_proto_depIdxs = nil
}
